### ISSUE TITLE
Add technical documents/descriptions

### ISSUE THREAD

**Issue by augustl** [smealum/SPACECRAFT#3]
I'd love to see some technical docs that explains how the engine works. In particular, I'd love to read about how you manage to project a cube based world (?) onto a sphere.

**Comment by Nsheppard01** [comment]
So there are 8 distorted cubes?

**Comment by posva** [comment]
@Nsheppard01 No, each distorted cube is a planet, I don't remember how many planets there are but that's more than 8 :smile:

**Comment by Nsheppard01** [comment]
No I mean when the cube becomes a globe, the cube's 8 vertexes become highly distorted blocks?

**Comment by ArthurSonzogni** [comment]
You can see initially a planet as a cube of 8 faces.
Then we subdivide each faces in 4 faces recursively until the resolution is high enough.
We get a sphere and not a cube because faces vertex are pushed in order to be at constant distance to the center of the sphere.

**Comment by posva** [comment]
Yeah, each face is subdivided and the initial cube becomes highly distorted. this distortion is visible in each of the 8 vertices of the initial cube which, as you can imagine, is where the distortion is at its highest  degree. Is that what you were looking for?
The best way to get yourself answers is to play with Spacecraft by yourself. It runs on Linux, Windows ans OS X.

We will love to hear what you think about it and any suggestions even if we are not going to implement them.
