### ISSUE TITLE
So what direction is this game going to go in?

### ISSUE THREAD

**Issue by Nsheppard01** [smealum/SPACECRAFT#5]
Is it just going to be a tech demo? Or is it going to eventualy become a more serious game?

Will space travel be soft sci-fi, will it be like KSP with orbits and delta-v, or will it be somewhere in the middle (real physics, but unrealistically efficient engines and FTL travel)

**Comment by posva** [comment]
This was a college project, none of use is going to extend this at least in a near future. You can therefore consider this as a tech demo.
