### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by MRePotatoes** [smealum/SPACECRAFT#6]
Can you meke a pre-compiled file plz

For smea: ça a l'air d'etre cool mais chuis un noob pour tout ce qui est compillage ... :+1:

**Comment by posva** [comment]
Il y en a deja une. Je te la cherche

**Comment by posva** [comment]
la voila https://dl.dropboxusercontent.com/u/13279485/spacecraft.zip

**Comment by MRePotatoes** [comment]
Merci! Au fait dsl je savais pas que tu était français toi aussi 😊

**Comment by posva** [comment]
Pas de souci :smiley:

**Comment by MRePotatoes** [comment]
Comment on active la gravité

-----Message d'origine-----
De : "Eduardo San Martin Morote" <notifications@github.com>
Envoyé : ‎18/‎12/‎2015 22:53
À : "smealum/SPACECRAFT" <SPACECRAFT@noreply.github.com>
Cc : "MRePotatoes" <evan97401@gmail.com>
Objet : Re: [SPACECRAFT] Releases (#6)

Closed #6.

**Comment by posva** [comment]
Je crois bien que c'était R pour se mettre en mode joueur
